language: csharp
solution: HelloWorld.sln
install:
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - build_number=$TRAVIS_BUILD_NUMBER
  - version_number=0.9.0
  - xbuild /p:Configuration=Release HelloWorld.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./bin/Release/HelloWorld.Tests.dll
  - zip -r build.zip src bin/Release/HelloWorld.dll readme.md 
